"""NavBridge — state holder + intent queue between SPEC verbs and dora topics.

NavBaseNode's verb handlers call methods on this object; the dora loop drains
queued intents and emits them to dora-nav's input topics. dora-nav's outputs
are pushed in via the on_*_update methods.
"""
from __future__ import annotations

from typing import Any, Protocol


class NavBridge(Protocol):
    def request_goal(self, pose: dict[str, Any]) -> None: ...
    def request_cmd_vel(self, cmd: dict[str, float]) -> None: ...
    def cancel(self) -> None: ...
    def latest_pose(self) -> dict[str, Any] | None: ...
    def current_status(self) -> str | None: ...
    def latest_obstacles(self) -> list[dict[str, Any]]: ...
    def on_pose_update(self, pose: dict[str, Any]) -> None: ...
    def on_status_update(self, status: str) -> None: ...
    def on_obstacles_update(self, obs: list[dict[str, Any]]) -> None: ...
